language: node_js
node_js:
  - "6"
  - "8"
before_script:
  - npm install -g gulp-cli jsdoc ava
  - curl -o- -L https://yarnpkg.com/install.sh | bash

script:
  - yarn install
  - npm run build
  - npm run test
    # Check that files didn't change after running grunt. It should be run before pushing any code change.
  - git diff --name-only --quiet -- dist src --
  - if ! git diff --name-only --quiet -- dist src --; then echo \"Files where modified after grunt execution!!...\"; exit 1; fi
